Repository curationexperts/iris, pull requests merged in 2018-04, with the labels that each got.

#75 Extract geotiff from zip file. Story #63
  .rubocop.yml
  app/importers/iris_record_importer.rb
  spec/fixtures/zipped_raster_example.csv
  spec/fixtures/zipped_raster_example.zip
  spec/importers/importer_spec.rb
Labels: in-dev

#77 updating README install instructions with ruby 2.4.4
  README.md
Labels: review

#87 Removed the CSV importer, now that it has been replaced with the ZIP importer
  .rubocop.yml
  .travis.yml
  README.md
  app/importers/coverage_validator.rb
  app/importers/import_file.rb
  app/importers/importer.rb
  app/importers/iris_csv_parser.rb
  app/importers/iris_mapper.rb
  app/importers/iris_record_importer.rb
  app/importers/provenance_validator.rb
  config/importer.yml
  lib/tasks/import.rake
  spec/fixtures/S_566_1914_clip.tif
  spec/fixtures/cambridge_grid.zip
  spec/fixtures/empty_row_example.csv
  spec/fixtures/example.csv
  spec/fixtures/example_with_no_visibility.csv
  spec/fixtures/missing_eastlimit.csv
  spec/fixtures/missing_limit_data.csv
  spec/fixtures/missing_northlimit.csv
  spec/fixtures/missing_provenance.csv
  spec/fixtures/missing_southlimit.csv
  spec/fixtures/missing_title.csv
  spec/fixtures/missing_westlimit.csv
  spec/fixtures/raster_example.csv
  spec/fixtures/vector_example.csv
  spec/fixtures/zipped_raster_example.csv
  spec/fixtures/zipped_raster_example.zip
  spec/importers/coverage_validator_spec.rb
  spec/importers/csv_parser_spec.rb
  spec/importers/importer_spec.rb
  spec/importers/iris_mapper_spec.rb
  spec/importers/provenance_validator_spec.rb
  spec/lib/tasks/import_rake_spec.rb
Labels: in progress
